services:  
  cutmind:
    container_name: cutmind
    image: u2pitchjami/cutmind:dev
    entrypoint: ["/bin/sh", "-c", "python3 -m cutmind.main"]
    environment:
      TZ: Europe/Paris
      HF_HOME: /app/hf_cache
    volumes:
      - /mnt/user/Zin-progress/CutMind/dev:/basedir
      - /mnt/user/Zin-progress/CutMind/dev/CutMind:/cutmind
      - /home/pipo/data/logs/cutmind/logs:/app/logs
      - /home/pipo/data/appdata/cutmind/env:/app/config
      - /mnt/user/appdata/cutmind/models:/app/hf_cache
    restart: always