services:
  comfyui-router-dev:
    container_name: comfyui-router-dev
    image: u2pitchjami/comfyui_video_router:cpu
    restart: unless-stopped
    command: ["python3", "-m", "comfyui_router.main"]
    
    # ğŸ§  Volumes montÃ©s (ton code et ton dossier de travail)
    volumes:
      - .:/app                   # code source local montÃ© en direct
      - /mnt/user/Zin-progress/comfyui-nvidia/basedir:/basedir  # dossier partagÃ© avec ComfyUI
      - /home/pipo/data/logs/comfyui_router:/app/logs
      - /home/pipo/data/appdata/comfyui_router/env:/app/config

    # ğŸŒ Variables dâ€™environnement
    environment:
      - TZ=Europe/Paris
      - PYTHONPATH=/app:/app
      - PYTHONUNBUFFERED=1

    # ğŸ§¾ Log direct dans le terminal
    tty: true
    stdin_open: true
